utils::globalVariables(c("x",
 "coverage",
 "chr_fwd" ,
 "chr_rev" ,
 "region" ,
 "color_region",
 "color_text.1" ,
 "color_text.2" ,
 "color_TU" ,
 "size_tu" ,
 "size_locusTag" ,
 "size_gene" ,
 "Limit" ,
 "shape" ,
 "col_outiler" ,
 "Alpha" ,
 "col_coverage" ,
 "shape_outlier" ,
 "limit_intensity" ,
 "face" ,
 "tick_length" ,
 "arrow.color" ,
 "minVelocity" ,
 "medianVelocity" ,
 "threshold_intensity" ,
 "col_above20" ,
 "fontface" ,
 "shape_above20" ,
 "axis_text_y_size" ,
 "axis_title_y_size" ,
 "TI_threshold" ,
 "p_value_TI" ,
 "p_value_manova" ,
 "termination_threshold" ,
 "iTSS_threshold" ,
 "p_value_int" ,
 "p_value_event" ,
 "p_value_hl" ,
 "event_duration" ,
 "HL_threshold" ,
 "vel_threshold" ,
 "HL_threshold_color" ,
 "vel_threshold_color" ,
 "ps_color" ,
 "iTSS_I_color"))